config/routes.rb
Rails.application.routes.draw do
  resources :occurrences
  
  devise_for :profiles, controllers: {
    registrations: 'profiles/registrations',
    sessions: 'profiles/sessions',
  }

  namespace :api do
    namespace :v1 do
      devise_for :profiles, controllers: { 
        sessions: 'api/v1/sessions',
        registrations: 'api/v1/registrations',
      }
    end
  end

  get 'home', to: 'home#index'
  root 'home#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4">
    <a class="navbar-brand" href="/">
        <%= image_tag("ios_logo.png", :alt => "sair", size: "120x70", class:"img-fluid" )%>
    </a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to home_path, { class: "nav-link active", "aria-current": "page" } do %> 
            <%= image_tag("home.png", :alt => "sair", size: "15x15", class:"img-fluid") %> 
            Menu
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to occurrences_path, { class: "nav-link active", "aria-current": "page" } do %> 
            <%= image_tag("telephone.png", :alt => "sair", size: "15x15", class:"img-fluid") %> 
            Ocorrências 
          <% end %>
        </li>
      </ul>   
      
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center justify-content-center p-3 link-dark text-decoration-none dropdown-toggle" id="dropdownUser3" data-bs-toggle="dropdown" aria-expanded="false">
          <%= image_tag("user.png", :alt => "sair", size: "30x30", class:"img-fluid") %>
        </a>
        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser3">
          <li><%= button_to "Logout", destroy_profile_session_path, method: :delete, class:"dropdown-item" %><li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_nonconformities_index.html.erb
    <table class="table table-striped table-bordered table-sm" >
    <thead>
      <tr>
        <th class="text-center">Local</th>
        <th class="text-center">Peça</th>
        <th class="text-center">Tipo</th>
        <th class="text-center">Nível</th>
        <th class="text-center">Quadrante</th>
        <th class="text-center">Medida</th>
        <th class="text-center">
          <%= link_to "Adicionar Dados", new_vehicle_nonconformity_path(@vehicle), class: "btn btn-primary" %>
        </th>
      </tr>
    </thead>
    <% @vehicle.nonconformities.each do |nonconformity| %>
    <tbody>
      <tr>
        <td class="text-center"><%= NonconformityLocal.find(nonconformity.nonconformityLocals).local %></td>
        <td class="text-center"><%= VehiclePart.find(nonconformity.vehicleParts).name %></td>
        <td class="text-center"><%= nonconformity.nonconformityTypes == "null" ? '' : NonconformityType.find(nonconformity.nonconformityTypes).nctype %></td>
        <td class="text-center"><%= NonconformityLevel.find(nonconformity.nonconformityLevels).level %></td>
        <td class="text-center"><%= nonconformity.quadrants == "null" ? '' : Quadrant.find(nonconformity.quadrants).option %></td>
        <td class="text-center"><%= Measure.find(nonconformity.measures).size %></td>


        <td class="justify-content-center d-flex">
          <%= link_to image_tag("see.png", :alt => "sair", size: "12x12", class:"img-fluid"), [@vehicle, nonconformity], class: "btn btn-link px-1" %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table> 
<br>